svn propset svn:eol-style native D:\ETHEA\InstantObjectsSVN\Demos\PrimerCross\Primer_D10_1.dpr
svn propset svn:eol-style native D:\ETHEA\InstantObjectsSVN\Demos\PrimerCross\Primer_D10_1.dproj
svn propset svn:eol-style native D:\ETHEA\InstantObjectsSVN\Demos\PrimerCross\Primer_D10_1.xml
svn propset svn:mime-type text/plain  D:\ETHEA\InstantObjectsSVN\Demos\PrimerCross\Primer_D10_1.dpr
svn propset svn:mime-type text/plain  D:\ETHEA\InstantObjectsSVN\Demos\PrimerCross\Primer_D10_1.dproj
svn propset svn:mime-type text/	plain D:\ETHEA\InstantObjectsSVN\Demos\PrimerCross\Primer_D10_1.xml
