@rem This file was generated by InstantSyncBatchFile.sh

@echo off
echo.
echo This script will replicate InstantVersion.res,
echo creating or overwriting all packages' resource files.
echo.
echo Press Enter to continue, Ctrl+C to cancel.
echo.
pause > nul
echo Copying...
echo.
copy "InstantVersion.res" "..\Source\Brokers\XML\DXE7\IOXML.res" > nul
echo ..\Source\Brokers\XML\DXE7\IOXML.res
copy "InstantVersion.res" "..\Source\Brokers\XML\DXE7\DclIOXML.res" > nul
echo ..\Source\Brokers\XML\DXE7\DclIOXML.res
copy "InstantVersion.res" "..\Source\Brokers\IBX\DXE7\IOIBX.res" > nul
echo ..\Source\Brokers\IBX\DXE7\IOIBX.res
copy "InstantVersion.res" "..\Source\Brokers\IBX\DXE7\DclIOIBX.res" > nul
echo ..\Source\Brokers\IBX\DXE7\DclIOIBX.res
copy "InstantVersion.res" "..\Source\Brokers\ADO\DXE7\IOADO.res" > nul
echo ..\Source\Brokers\ADO\DXE7\IOADO.res
copy "InstantVersion.res" "..\Source\Brokers\ADO\DXE7\DclIOADO.res" > nul
echo ..\Source\Brokers\ADO\DXE7\DclIOADO.res
copy "InstantVersion.res" "..\Source\Brokers\BDE\DXE7\IOBDE.res" > nul
echo ..\Source\Brokers\BDE\DXE7\IOBDE.res
copy "InstantVersion.res" "..\Source\Brokers\BDE\DXE7\DclIOBDE.res" > nul
echo ..\Source\Brokers\BDE\DXE7\DclIOBDE.res
copy "InstantVersion.res" "..\Source\Brokers\DBX\DXE7\IODBX.res" > nul
echo ..\Source\Brokers\DBX\DXE7\IODBX.res
copy "InstantVersion.res" "..\Source\Brokers\DBX\DXE7\DclIODBX.res" > nul
echo ..\Source\Brokers\DBX\DXE7\DclIODBX.res
copy "InstantVersion.res" "..\Source\Core\DXE7\IOCore.res" > nul
echo ..\Source\Core\DXE7\IOCore.res
copy "InstantVersion.res" "..\Source\Design\DXE7\DclIOCore.res" > nul
echo ..\Source\Design\DXE7\DclIOCore.res
copy "InstantVersion.res" "..\Source\Catalogs\MSSql\DXE7\IOMSSqlCatalog.res" > nul
echo ..\Source\Catalogs\MSSql\DXE7\IOMSSqlCatalog.res
copy "InstantVersion.res" "..\Source\Catalogs\IBFb\DXE7\IOIBFbCatalog.res" > nul
echo ..\Source\Catalogs\IBFb\DXE7\IOIBFbCatalog.res
echo.
echo Done.
