#!/bin/sh
#
#   InstantObjects
#   Release Tools
#

# ##### BEGIN LICENSE BLOCK #####
# Version: MPL 1.1
#
# The contents of this file are subject to the Mozilla Public License Version
# 1.1 (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
# http://www.mozilla.org/MPL/
#
# Software distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
# for the specific language governing rights and limitations under the
# License.
#
# The Original Code is: InstantObjects Release Tools
#
# The Initial Developer of the Original Code is: Joao Morais
#
# Portions created by the Initial Developer are Copyright (C) 2006
# the Initial Developer. All Rights Reserved.
#
# Contributor(s):
#
#
# ##### END LICENSE BLOCK #####

InstantVersionResFile="InstantVersion.res"
InstantScriptFile="InstantReplicateResource.bat"

echo
echo "This script will (re)create ${InstantScriptFile}."
echo "Press Enter to continue, Ctrl+C to cancel."
read

echo -n -e \
"@rem This file was generated by InstantSyncBatchFile.sh\r\n"\
"\r\n"\
"@echo off\r\n"\
"echo.\r\n"\
"echo This script will replicate ${InstantVersionResFile},\r\n"\
"echo creating or overwriting all packages' resource files.\r\n"\
"echo.\r\n"\
"echo Press Enter to continue, Ctrl+C to cancel.\r\n"\
"echo.\r\n"\
"pause > nul\r\n"\
"echo Copying...\r\n"\
"echo.\r\n" > ${InstantScriptFile}

find .. -name "*.dpk" -type f | sed 's/\//\\\\/g' | while read DpkFile
do
  echo -e "copy \"${InstantVersionResFile}\" \"${DpkFile/.dpk/.res}\" > nul\r"
  echo -e "echo ${DpkFile/.dpk/.res}\r"
done >> ${InstantScriptFile}
echo -n -e \
"echo.\r\n"\
"echo Done.\r\n" >> ${InstantScriptFile}
echo "Done."
